apiVersion: mongodb.com/v1
kind: MongoDB

metadata:
  name: {{ .Values.mongodb.name }}
  namespace: mongodb

spec:
  type: ReplicaSet
  members: 3
  version: "8.0.0"

  opsManager:
    configMapRef:
      name: my-project

  credentials: organization-secret
