{{ range $user := concat (.Values.mongodbUsers | default (list)) (.Values.mongodbRequestUsers | default (list)) }}
---
apiVersion: mongodb.com/v1
kind: MongoDBUser

metadata:
  name: {{ $user.resourceName }}
  namespace: {{ $.Release.Namespace }}

spec:
  username: {{ $user.username | quote }}
  db: {{ $user.authDatabase | quote }}

  mongodbResourceRef:
    name: {{ $.Values.mongodb.name }}

  passwordSecretKeyRef:
    name: {{ $user.passwordSecret }}
    key: {{ $user.passwordKey }}

  connectionStringSecretName: {{ $user.connectionStringSecret }}
{{- if $user.roles }}

  roles:
{{ range $role := $user.roles }}
    - db: {{ $role.db | quote }}
      name: {{ $role.name | quote }}
{{ end }}
{{- else }}

  roles: []
{{- end }}
{{ end }}
