apiVersion: mongodb.com/v1
kind: MongoDB

metadata:
  name: {{ .Values.mongodb.name }}
  namespace: mongodb

spec:
  type: ReplicaSet
  members: {{ .Values.mongodb.members }}
  version: {{ .Values.mongodb.version | quote }}

opsManager:
  configMapRef:
    name: {{ .Values.mongodb.opsManagerConfigMap }}

credentials: organization-secret
