mongodb:
  name: mongodb-development
  members: 3
  version: "8.0.0"
  opsManagerConfigMap: my-project
  credentialsSecret: organization-secret

mongodbUsers:
  - resourceName: mongodb-admin
    username: mongodb-admin
    authDatabase: admin
    passwordSecret: mongodb-admin-password
    passwordKey: password
    connectionStringSecret: mongodb-admin-connection
    roles:
      - db: admin
        name: root
  - resourceName: app-user
    username: app-user
    authDatabase: admin
    passwordSecret: app-user-password
    passwordKey: password
    connectionStringSecret: app-user-connection
    roles:
      - db: application
        name: readWrite
